[package]
name = "runner"
version = "0.1.0"
edition = "2021"
authors = ["Paul T <paul.t@gembaadvantage.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
